# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    tags:
      ftp-upload_*:
        - step:
          name: push to ftp server
          development: staging
          caches:
            - node
          script:
            - npm install
            - npm test
            # - apt-get update
            # - apt-get -qq install git-ftp
            # - git ftp push --user $FTP_USERNAME --password $FTP_PASSWORD ftp://$FTP_HOST
